### ISSUE TITLE
cannot delete tag with a space [ ] as first charachter

### ISSUE THREAD

**Issue by hchaase** [kookma/TW-Commander#15]
I had some tags where, by accident they had a space in front of the text.

I tried to use commander to add a correct tag and delete the one with space in front. 

1. search for [tag[ issue]
2- select all tiddlers
3. add new tag (ok)
4. delete old tag [ issue]

I tried "delete tag" and replace tag but neither worked and the log just show
"2020-02-10 11:58:57 remove-old-tag-bulk" but with no entries below the text.

**Comment by kookma** [comment]
@hchaase 
As TW 5.1.21 removes the leading spaces, I think it should not possible to add such tags!
by the way Commander strips out leading and trailing spaces when you enter a tag!

by the way can you list those tiddlers using other tools like

`<<list-links filter:"[tag[ issue]]">>`

**Comment by hchaase** [comment]
Venlig hilsen
HC Haase



Den man. 10. feb. 2020 kl. 13.08 skrev Mohammad Rahmani <
notifications@github.com>:

> @hchaase <https://github.com/hchaase>
> As TW 5.1.21 removes the leading spaces, I think it should not possible to
> add such tags!
>
Well it is. In tiddlywiki.com 5.1.21 the leading space is kept if entered
in front of a tag. See screenshot

But I agree that it should not be possible.
[image: billede.png]




by the way Commander strips out leading and trailing spaces when you enter
> a tag!
>
that's good.

> by the way can you list those tiddlers using other tools like
>
> <<list-links filter:"[tag[ issue]]">>
>

yes I can.

maybe there is a bug in TW. It is definitely a fringe case.

**Comment by kookma** [comment]
@hchaase 
I recommend to discuss this in the forum! I am ready to push a new update if the issue was in Commander side!

**Comment by kookma** [comment]
This has been addressed in Commander 2.1.4
