### ISSUE TITLE
Option to prevent updating modified field

### ISSUE THREAD

**Issue by tejasvi** [kookma/TW-Commander#18]
Some of the operations performed are mundane (like changing id field) and 100s of tiddlers showing up in recent tab is unhelpful. A toggle to prevent that would be very useful.

**Comment by kookma** [comment]
Hi @tejasvi - If I understand you correctly, your request is to prevent changes to be displayed in the recent tab. If so, you can turn off timestamp in Tiddlywiki from right sidebar under tools.

**Comment by tejasvi** [comment]
TIL. Thanks a lot!!
