### ISSUE TITLE
Set field value to the value of another field

### ISSUE THREAD

**Issue by jbardi** [kookma/TW-Commander#19]
I'm not sure if I may have missed this ability, but as far as I can tell, you can only replace hard coded text in a field. I have the need to set the value of one field to the value of another field for a few hundred tiddlers. Would be nice to have the option for 2 dropdown menus, one as source field and the other for target field.

**Comment by kookma** [comment]
There are two solutions

1. Destructive method - use the rename field, if both fields are in the same tiddler and you need the new one
2. Limited solution If all tiddlers field say fieldx shall get the value of tiddler y - fieldy then why not manually put the value in fieldy into Set Field Value inbutbox

NOTE: As one may need to put wikitext into fields, so Commander prefers to set values as literal and not transclude them.

I close this issue; I can propose some wikitext to do this. I may recommend to raise your question in Talk forum to see if there is any general solution for this.
