### ISSUE TITLE
Installation on Node.js failed

### ISSUE THREAD

**Issue by ghost** [kookma/TW-Commander#22]
Hi,
I'm experiencing problems with the installation on Node.js... I've followed the guide, stop server, copy source/commander to tiddlywiki/plugins/kookma/, modify tiddlywiki.info and start server. But when I browse to $:/Commander I'm getting an funny looking tiddler. Also the icon for Commander is not in the page controls.
Below a screenshot.
![TW-Comander_Screenshot from 2021-09-16 11-43-44](https://user-images.githubusercontent.com/5459002/133592263-91b079e3-68b3-4451-b513-e77f2f1c660f.png)

**Comment by Marxsal** [comment]
I just did a quick test with the local install and it works fine for me. Maybe later I'll try the global install.

Is it possible you still have the *.tid version (local) file-based version installed?

If you have other plugins installed, I would try disabling all of them, reloading, and seeing how it runs on its own.

**Comment by Marxsal** [comment]
Also worked for me with global install.

**Comment by kookma** [comment]
Please see installation guide. I rechecked and it works fine both with local and global installation of node.js

By the way I have updated the installation instruction in the coming commander 2.1.4
