### ISSUE TITLE
Add fields not working if plugin "JSON Mangler" is enabled

### ISSUE THREAD

**Issue by ghost** [kookma/TW-Commander#23]
Hi,

Maybe this is not TW-Commander's fault, but I'd like to report this phenomenon I saw.

I have the plugin "JSON Mangler" (https://github.com/joshuafontany/TW5-JsonMangerPlugin) installed, and as a result, my TW-Commander's "Field > Add fields" couldn't work because every time I type something into "field name" or "field value" input, the just typed in character get deleted immediately. If I disable "JSON Mangler" plugin, than it works normally.

**Comment by kookma** [comment]
@joshuafontany!

Hi Joshua,
 Would you please have a look? TW-Commander should work with fields without considering the tiddler type!

**Comment by kookma** [comment]
I close this issue, as there is nothing to be done in commander side.
