### ISSUE TITLE
Not functioning on TiddlyDesktop

### ISSUE THREAD

**Issue by GwenGunn** [kookma/TW-Commander#24]
Hey, just downloaded this plugin. Not a super accomplished coder here, but I installed it on TiddlyDesktop, and the image won't display on the toolbar, just a blank area, and when I try to open it as its own window through the manager, it gives me a javascript error and asks me to reload. Any idea what to do?

**Comment by kookma** [comment]
Why did you close the issue? Have you solved it? I do not use TiddlyDesktop, but many use Coammander on it and we have no any problem reported!
