### ISSUE TITLE
Old Tag drop-down list

### ISSUE THREAD

**Issue by wahidmounir** [kookma/TW-Commander#25]
the drop down list of old tag in tag tab doesn't work it wont open 

even after checking the demo website in which the drop-down list doesn't open

**Comment by kookma** [comment]
It works for me, tested again on tiddlywiki.com!

Note: You have to enter something in Combo search
and your search shall produces some output
and your output shall have some tags to see the drop down!

If you have no results, or your result has no tag! then you cannot see anything!
![img_874_msedge](https://user-images.githubusercontent.com/830394/150907714-40749051-a216-46a9-921a-f988df37b073.gif)
