### ISSUE TITLE
New fields is added as lower case

### ISSUE THREAD

**Issue by myfta** [kookma/TW-Commander#27]
If you add a new field to a selection of tiddlers with a field name of, say, "NewField" it is added as "newfield". Can this be fixed? 

Renaming the field does not work either from "newfield" to "NewField".

**Comment by kookma** [comment]
Thank you @myfta 
This is by design and. Field with name in mixed case is new to TiddlyWiki.
This will be fixed in 5.3.0 (https://github.com/kookma/TW-Commander/issues/28)

**Comment by myfta** [comment]
5.3.0 of TW, not an update to TW-Commander?

**Comment by kookma** [comment]
I may upload the dev branch! but no new update util 5.30
Feel free to submit a PR, it can be merged as a patch!

**Comment by kookma** [comment]
Fix is coming in Commander 2.1.4
