### ISSUE TITLE
Spaces in buttons need to be dealt with

### ISSUE THREAD

**Issue by keatonlao** [kookma/TW-Commander#32]
`$:/plugins/kookma/commander/buttons/pagecontrol`

Here are my modifications:

```
\whitespace trim
\define commander-button(class)
\whitespace trim
<$button to="$:/Commander" tooltip={{$:/language/Buttons/Commander/Hint}} aria-label={{$:/language/Buttons/Commander/Caption}} class="""$(tv-config-toolbar-class)$ $class$""">
<$list filter="[<tv-config-toolbar-icons>match[yes]]">
{{$:/plugins/kookma/commander/images/commander.svg}}
</$list>
<$list filter="[<tv-config-toolbar-text>match[yes]]">
<span class="tc-btn-text"><$text text={{$:/language/Buttons/Commander/Caption}}/></span>
</$list>
</$button>
\end

<$list filter="[list[$:/StoryList]] +[field:title[$:/Commander]]" emptyMessage=<<commander-button>>>
<<commander-button "tc-selected">>
</$list>
```

> OCD, can't accept one more or less space

**Comment by kookma** [comment]
Hi @keatonlao 
I did not follow what is the issue. The commander button is based on $:/core/ui/Buttons/control-panel
Did you see extra space in page control?

**Comment by keatonlao** [comment]
You can see it in `$:/core/ui/ControlPanel/Toolbars/PageControls`.

> If you don't show the page button, the same can be seen in the More drop-down menu: `$:/core/ui/Buttons/more-page-actions`.

I found that the `$:/plugins/kookma/utility/ui/Buttons/ViewFields` button also has space problems.

To check page buttons for space problems, I usually check these items:

- $:/core/ui/SideBarSegments/page-controls
- $:/core/ui/SideBar/Tools
- $:/core/ui/ControlPanel/Toolbars/PageControls
- $:/core/ui/Buttons/more-page-actions

> After hiding the buttons, repeat the check again

Thanks @kookma

**Comment by kookma** [comment]
Ah I got it thank you!
A fix is coming in few minutes.
